<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="admin.aspx.cs" Inherits="MaxBarbell.admin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <h1> Admin Page </h1>

    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="ItemID" DataSourceID="SqlDataSource1">
        <Columns>
            <asp:BoundField DataField="ItemID" HeaderText="ItemID" ReadOnly="True" SortExpression="ItemID" />
            <asp:BoundField DataField="ItemPrice" HeaderText="ItemPrice" SortExpression="ItemPrice" />
            <asp:BoundField DataField="ItemName" HeaderText="ItemName" SortExpression="ItemName" />
            <asp:BoundField DataField="ItemStock" HeaderText="ItemStock" SortExpression="ItemStock" />
            <asp:HyperLinkField DataNavigateUrlFields="ItemID" DataNavigateUrlFormatString="UploadImage.aspx?UserID=(0)" InsertVisible="False" Text="Set Image" />
        </Columns>
</asp:GridView>


<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:IdentityConnectionString %>" SelectCommand="SELECT [ItemID], [ItemPrice], [ItemName], [ItemStock] FROM [tblItems]" ConflictDetection="CompareAllValues" DeleteCommand="DELETE FROM [tblItems] WHERE [ItemID] = @original_ItemID AND [ItemPrice] = @original_ItemPrice AND [ItemName] = @original_ItemName AND (([ItemStock] = @original_ItemStock) OR ([ItemStock] IS NULL AND @original_ItemStock IS NULL))" InsertCommand="INSERT INTO [tblItems] ([ItemID], [ItemPrice], [ItemName], [ItemStock]) VALUES (@ItemID, @ItemPrice, @ItemName, @ItemStock)" OldValuesParameterFormatString="original_{0}" UpdateCommand="UPDATE [tblItems] SET [ItemPrice] = @ItemPrice, [ItemName] = @ItemName, [ItemStock] = @ItemStock WHERE [ItemID] = @original_ItemID AND [ItemPrice] = @original_ItemPrice AND [ItemName] = @original_ItemName AND (([ItemStock] = @original_ItemStock) OR ([ItemStock] IS NULL AND @original_ItemStock IS NULL))">
    <DeleteParameters>
        <asp:Parameter Name="original_ItemID" Type="Int32" />
        <asp:Parameter Name="original_ItemPrice" Type="Decimal" />
        <asp:Parameter Name="original_ItemName" Type="String" />
        <asp:Parameter Name="original_ItemStock" Type="String" />
    </DeleteParameters>
    <InsertParameters>
        <asp:Parameter Name="ItemID" Type="Int32" />
        <asp:Parameter Name="ItemPrice" Type="Decimal" />
        <asp:Parameter Name="ItemName" Type="String" />
        <asp:Parameter Name="ItemStock" Type="String" />
    </InsertParameters>
    <UpdateParameters>
        <asp:Parameter Name="ItemPrice" Type="Decimal" />
        <asp:Parameter Name="ItemName" Type="String" />
        <asp:Parameter Name="ItemStock" Type="String" />
        <asp:Parameter Name="original_ItemID" Type="Int32" />
        <asp:Parameter Name="original_ItemPrice" Type="Decimal" />
        <asp:Parameter Name="original_ItemName" Type="String" />
        <asp:Parameter Name="original_ItemStock" Type="String" />
    </UpdateParameters>
    </asp:SqlDataSource>
    <br />
    <br />
    <asp:FormView ID="FormView1" runat="server" DataKeyNames="ItemID" DataSourceID="SqlDataSource1" DefaultMode="Insert" OnPageIndexChanging="FormView1_PageIndexChanging">
        <EditItemTemplate>
            ItemID:
            <asp:Label ID="ItemIDLabel1" runat="server" Text='<%# Eval("ItemID") %>' />
            <br />
            ItemPrice:
            <asp:TextBox ID="ItemPriceTextBox" runat="server" Text='<%# Bind("ItemPrice") %>' />
            <br />
            ItemName:
            <asp:TextBox ID="ItemNameTextBox" runat="server" Text='<%# Bind("ItemName") %>' />
            <br />
            ItemStock:
            <asp:TextBox ID="ItemStockTextBox" runat="server" Text='<%# Bind("ItemStock") %>' />
            <br />
            <asp:LinkButton ID="UpdateButton" runat="server" CausesValidation="True" CommandName="Update" Text="Update" />
            &nbsp;<asp:LinkButton ID="UpdateCancelButton" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel" />
        </EditItemTemplate>
        <InsertItemTemplate>
            ItemID:
            <asp:TextBox ID="ItemIDTextBox" runat="server" Text='<%# Bind("ItemID") %>' />
            <br />
            ItemPrice:
            <asp:TextBox ID="ItemPriceTextBox" runat="server" Text='<%# Bind("ItemPrice") %>' />
            <br />
            ItemName:
            <asp:TextBox ID="ItemNameTextBox" runat="server" Text='<%# Bind("ItemName") %>' />
            <br />
            ItemStock:
            <asp:TextBox ID="ItemStockTextBox" runat="server" Text='<%# Bind("ItemStock") %>' />
            <br />
            <asp:LinkButton ID="InsertButton" runat="server" CausesValidation="True" CommandName="Insert" Text="Insert" />
            &nbsp;<asp:LinkButton ID="InsertCancelButton" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel" />
        </InsertItemTemplate>
        <ItemTemplate>
            ItemID:
            <asp:Label ID="ItemIDLabel" runat="server" Text='<%# Eval("ItemID") %>' />
            <br />
            ItemPrice:
            <asp:Label ID="ItemPriceLabel" runat="server" Text='<%# Bind("ItemPrice") %>' />
            <br />
            ItemName:
            <asp:Label ID="ItemNameLabel" runat="server" Text='<%# Bind("ItemName") %>' />
            <br />
            ItemStock:
            <asp:Label ID="ItemStockLabel" runat="server" Text='<%# Bind("ItemStock") %>' />
            <br />

            <asp:LinkButton ID="EditButton" runat="server" CausesValidation="False" CommandName="Edit" Text="Edit" />
            &nbsp;<asp:LinkButton ID="DeleteButton" runat="server" CausesValidation="False" CommandName="Delete" Text="Delete" />
            &nbsp;<asp:LinkButton ID="NewButton" runat="server" CausesValidation="False" CommandName="New" Text="New" />

        </ItemTemplate>
    </asp:FormView>
    <br />
    <br />


</asp:Content>
